### ISSUE TITLE
Strava API "Forever tokens" ends soon

### ISSUE THREAD

**Issue by Ymerlet** [kekepins/strava-movescount-to-kikourou#7]
As stated here: https://github.com/kekepins/strava-movescount-to-kikourou/issues/new , every API app will ave to use OAuth soon. As far as I can see, this will break Strava sync in the app.

**Comment by kekepins** [comment]
Thanks, yes I received also a mail, I gonna check this  asap

**Comment by kekepins** [comment]
We have one year : 

> We want to make this change easier on you, so you will have from now through October 15, 2019, to migrate to the new version of OAuth using short-lived access tokens and refresh tokens. During the migration period, existing forever access tokens will continue to work.

**Comment by kekepins** [comment]
New version (1.4.0) is ok with Oauth2.
First access a web page is opened and ask authorisation.
A web server is created by application to receive code (one time), code is saved locally.
With code + secret + client id, a fresh token is asked when application access strava.
